[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.0.0"
httparse = "1.8.0"
image = "0.24.7"
mime_guess = "2.0.4"
rusqlite = "0.30.0"
threadpool = "1.0"
